# open cmd
# docker pull mysql
# docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=1234 --name mysql mysql
# docker ps
# docker exec -it mysql bash
# mysql -u root -p
# create database spring_data_redis_example;
# use spring_data_redis_example;
#```

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_data_redis_example
    username: root
    password: 1234

logging:
  level:
    org.hibernate.SQL: info # 로그 레밸 설정, jpa에서 생성되는 sql이 로그를 통해서 출력됨 (show_sql은 sout으로 출력됨)
    org.hibernate.type: trace # 쿼리 찍힐때 (?, ?) 같은 쿼리 파라미터에서 ?가 무슨 값을 가졌는지 알려준다.



